"""Code Interpreter as the PROOF SURFACE for the deterministic CRS math.

Read the framing before judging the design. MapleGuard's CRS engine is trusted library
code, so a sandbox is NOT a safety boundary here: we are not running model-generated code,
and nothing the model emits reaches this path. The value is presentational. The CRS number
is recomputed in a visible, isolated, reproducible sandbox straight from the published grid,
so the demo can SHOW that the score was computed, not generated by the model. In-process
`crs()` stays the source of truth; the sandbox is the reproducible mirror, and we cross-check
that the two agree and refuse to report a mismatch.

Two backends behind one tiny `CodeSandbox` interface (`execute_code -> SandboxResult`):

  - dev:    `LocalSubprocessSandbox` runs the snippet in a fresh `python3 -c` subprocess with
            PYTHONPATH at the repo root. A real, isolated, reproducible mirror that needs no
            AWS, so the proof surface is exercised offline against the same engine.
  - deploy: `AgentCoreCodeSandbox` wraps `bedrock_agentcore`'s Code Interpreter. It uploads
            the deterministic `crs`/`agent` source into the sandbox, runs the same snippet,
            and parses the `executeCode` result stream. The client surface is import-verified
            against bedrock-agentcore 1.22.0 (`CodeInterpreter.start/execute_code/stop`,
            `code_session`); the live run needs a provisioned Code Interpreter, see
            docs/agentcore-runbook.md. The stream-shape parsing is derived from the SDK's own
            `download_file` reader and marked where it cannot be exercised offline.

`bedrock_agentcore` is imported lazily inside the deploy backend, so this module imports and
tests with no AWS SDK present.
"""
from __future__ import annotations

import json
import pathlib
import subprocess
import sys
from dataclasses import dataclass, field
from typing import Any, Optional

# The marker the snippet prints its JSON result behind, so we parse exactly one line of
# stdout and never mistake an incidental print for the score.
RESULT_MARKER = "__MAPLEGUARD_CRS__"

# Repo root (parent of the agent/ package), so a subprocess can import crs/ and agent/.
REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]


@dataclass
class SandboxResult:
    """One code execution's captured output, normalized across backends."""
    stdout: str
    stderr: str = ""
    exit_code: int = 0
    via: str = "local"


@dataclass
class ReproducibleScore:
    """The proof-surface result: the in-process score (source of truth) beside the same
    number recomputed in the sandbox, plus whether they agree.

    `matches` is the claim the demo rests on. A mismatch is never reported as a score: the
    caller sees `matches=False` and the two totals, which is the honest failure mode.
    """
    in_process: dict                 # serde.score_to_dict(crs(...)) — the source of truth
    sandbox_total: Optional[int]     # total recomputed inside the sandbox
    matches: bool                    # sandbox_total == in_process["total"]
    via: str                         # which sandbox produced the mirror ("local"/"agentcore")
    snippet: str                     # the exact code the sandbox ran (shown in the demo)
    stdout: str = ""                 # raw sandbox stdout (photographs the reproducible run)
    sandbox_score: Optional[dict] = None  # full breakdown recomputed in the sandbox

    def as_dict(self) -> dict:
        return {
            "in_process": self.in_process,
            "sandbox_total": self.sandbox_total,
            "sandbox_score": self.sandbox_score,
            "matches": self.matches,
            "via": self.via,
            "snippet": self.snippet,
            "stdout": self.stdout,
        }


def crs_sandbox_snippet(profile: dict, as_of: Optional[str] = None) -> str:
    """The self-contained Python the sandbox runs: rebuild the typed Profile from the dict
    with the SAME serde the tools use, call the SAME `crs()` engine, and print the score as
    JSON behind `RESULT_MARKER`. No arithmetic is written here; the published-grid engine
    does it. Reproducible: identical input dict -> identical printed line.
    """
    payload = json.dumps({"profile": profile, "as_of": as_of})
    return (
        "import json\n"
        "from agent import serde\n"
        "from crs import crs\n"
        f"_in = json.loads({payload!r})\n"
        "_p = serde.profile_from_dict(_in['profile'])\n"
        "_score = crs(_p, serde._parse_date(_in['as_of']))\n"
        f"print({RESULT_MARKER!r} + json.dumps(serde.score_to_dict(_score)))\n"
    )


def parse_crs_stdout(stdout: str) -> Optional[dict]:
    """Pull the score dict out of sandbox stdout: the JSON that follows `RESULT_MARKER` on
    its line. Returns None if the marker never appeared (an execution error), so the caller
    reports a non-match rather than inventing a number."""
    for line in stdout.splitlines():
        idx = line.find(RESULT_MARKER)
        if idx != -1:
            try:
                return json.loads(line[idx + len(RESULT_MARKER):])
            except json.JSONDecodeError:
                return None
    return None


# ----------------------------------------------------------------- dev backend (offline)
class LocalSubprocessSandbox:
    """Runs a snippet in a fresh `python3 -c` subprocess rooted at the repo. A real,
    isolated, reproducible mirror with no AWS: a separate process, importing the same engine,
    recomputes the number from the published grid. This is the offline proof surface."""

    via = "local"

    def __init__(self, repo_root: Optional[pathlib.Path] = None,
                 python: Optional[str] = None, timeout: int = 30):
        self.repo_root = pathlib.Path(repo_root) if repo_root else REPO_ROOT
        self.python = python or sys.executable
        self.timeout = timeout

    def execute_code(self, code: str, language: str = "python") -> SandboxResult:
        if language != "python":
            raise ValueError(f"LocalSubprocessSandbox runs python, not {language!r}")
        import os
        env = dict(os.environ)
        existing = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = (str(self.repo_root) + (os.pathsep + existing if existing else ""))
        proc = subprocess.run(
            [self.python, "-c", code], cwd=str(self.repo_root), env=env,
            capture_output=True, text=True, timeout=self.timeout,
        )
        return SandboxResult(stdout=proc.stdout, stderr=proc.stderr,
                             exit_code=proc.returncode, via=self.via)


# -------------------------------------------------------------- deploy backend (AgentCore)
# Source files the sandbox needs to import `crs` and `agent.serde`. Uploaded before the first
# run so the sandbox computes with the exact repo engine, not a reworded copy.
_SANDBOX_SOURCE_MODULES = (
    "crs/__init__.py",
    "agent/__init__.py",
    "agent/serde.py",
)


class AgentCoreCodeSandbox:
    """Wraps `bedrock_agentcore` Code Interpreter so the CRS math runs in the managed sandbox.

    Import-verified surface (bedrock-agentcore 1.22.0):
      `bedrock_agentcore.tools.code_interpreter_client.CodeInterpreter(region)`,
      `.start(...) -> session_id`, `.execute_code(code, language) -> dict`, `.stop()`,
      and the `code_session(region)` context manager.

    NOT verified offline (needs a live Code Interpreter): the `executeCode` result-stream
    shape and the source upload. The stream parsing below mirrors the SDK's own
    `download_file` reader (iterate `result["stream"]`, read `event["result"]["content"]`),
    plus the documented `structuredContent` stdout/stderr/exitCode fields, and is marked as
    such. Provisioning: docs/agentcore-runbook.md.
    """

    via = "agentcore"

    def __init__(self, client: Any, upload_source: bool = True):
        """`client` is a started `CodeInterpreter` (or any object exposing `execute_code`
        and, when `upload_source`, `upload_file`). Build one with `build_agentcore_sandbox`."""
        self.client = client
        self._prepared = not upload_source

    def prepare(self, repo_root: Optional[pathlib.Path] = None) -> None:
        """Upload the deterministic engine into the sandbox so the snippet's imports resolve
        to the repo code. Skipped if the sandbox image already ships it (`upload_source=False`).
        """
        if self._prepared:
            return
        root = pathlib.Path(repo_root) if repo_root else REPO_ROOT
        for rel in _SANDBOX_SOURCE_MODULES:
            src = (root / rel)
            if src.exists():
                self.client.upload_file(rel, src.read_text())
        self._prepared = True

    def execute_code(self, code: str, language: str = "python") -> SandboxResult:
        self.prepare()
        raw = self.client.execute_code(code, language=language)
        return self._parse(raw)

    @staticmethod
    def _parse(raw: Any) -> SandboxResult:
        """Normalize an `executeCode` response into a SandboxResult.

        Handles the documented shapes: a `structuredContent` object with stdout/stderr/
        exitCode, and/or a `content` list of `{type:"text", text:...}` blocks (the shape the
        SDK's own `download_file` iterates). Marked docs-derived: not exercised offline."""
        stdout_parts: list[str] = []
        stderr = ""
        exit_code = 0
        if isinstance(raw, dict) and "stream" in raw:
            for event in raw["stream"]:
                result = event.get("result") if isinstance(event, dict) else None
                if not isinstance(result, dict):
                    continue
                structured = result.get("structuredContent")
                if isinstance(structured, dict):
                    if "stdout" in structured:
                        stdout_parts.append(str(structured.get("stdout", "")))
                    stderr = str(structured.get("stderr", stderr) or stderr)
                    exit_code = int(structured.get("exitCode", exit_code) or exit_code)
                for item in result.get("content", []) or []:
                    if isinstance(item, dict) and item.get("type") == "text":
                        stdout_parts.append(item.get("text", ""))
                if result.get("isError"):
                    exit_code = exit_code or 1
        elif isinstance(raw, dict):
            # A already-unwrapped dict (some client wrappers return the structured content).
            stdout_parts.append(str(raw.get("stdout", "")))
            stderr = str(raw.get("stderr", "") or "")
            exit_code = int(raw.get("exitCode", 0) or 0)
        return SandboxResult(stdout="".join(stdout_parts), stderr=stderr,
                             exit_code=exit_code, via="agentcore")


def build_agentcore_sandbox(region: str, identifier: Optional[str] = None,
                            upload_source: bool = True, **client_kwargs: Any
                            ) -> AgentCoreCodeSandbox:
    """Construct and start a Code Interpreter, wrapped as an `AgentCoreCodeSandbox`.

    Requires `bedrock-agentcore` and live AWS. Imported lazily so this module needs neither
    to import. `identifier` selects the interpreter (default `aws.codeinterpreter.v1`).
    """
    from bedrock_agentcore.tools.code_interpreter_client import CodeInterpreter

    client = CodeInterpreter(region=region, **client_kwargs)
    client.start(**({"identifier": identifier} if identifier else {}))
    return AgentCoreCodeSandbox(client, upload_source=upload_source)


# ----------------------------------------------------------------------- the proof surface
def run_crs_in_sandbox(profile: dict, as_of: Optional[str] = None,
                       sandbox: Optional[Any] = None) -> ReproducibleScore:
    """Compute the CRS in-process (the source of truth) and mirror it in a sandbox, then
    cross-check the two totals agree.

    `sandbox` is any object with `execute_code(code) -> SandboxResult`; defaults to the
    offline `LocalSubprocessSandbox`. Pass an `AgentCoreCodeSandbox` to run the mirror in the
    managed Code Interpreter for the demo. A mismatch (or an errored run) returns
    `matches=False` with both totals, never a fabricated number.
    """
    from crs import crs
    from . import serde

    truth = serde.score_to_dict(crs(serde.profile_from_dict(profile), serde._parse_date(as_of)))

    sandbox = sandbox or LocalSubprocessSandbox()
    snippet = crs_sandbox_snippet(profile, as_of)
    result = sandbox.execute_code(snippet)
    mirrored = parse_crs_stdout(result.stdout)
    sandbox_total = mirrored.get("total") if mirrored else None

    return ReproducibleScore(
        in_process=truth,
        sandbox_total=sandbox_total,
        sandbox_score=mirrored,
        matches=(mirrored is not None and sandbox_total == truth["total"]),
        via=getattr(sandbox, "via", "local"),
        snippet=snippet,
        stdout=result.stdout,
    )
